jwtCookieAuth:
  secretSeed: 123456
  secure: true
  httpOnly: true
  sessionExpiryVolatile: PT20m
  sessionExpiryPersistent: P7d
swagger:
  resourcePackage: console.resources
database:
  driverClass: org.h2.Driver
  user: sa
  password: ''
  url: jdbc:h2:./target/test
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
server:
  applicationConnectors:
  - type: http 
    port: 9080
  adminConnectors:
  - type: http
    port: 9081